### PR TITLE
Update Mimic integration to 0.7

### PR DESCRIPTION
**Pull request by osipxd**

### CODE REVIEW

**Comment by Travja** [comment]
Wow okay. I'm not sure how I forgot/missed this for so long. @osipxd If you want to update this to latest code, we can get things merged in. Otherwise I can piece together what you've got and get the update done myself at some point.

**Comment by osipxd** [comment]
Ok, I'll update this PR soon

**Comment by Travja** [comment]
@osipxd Should I look into updating this myself?

**Comment by osipxd** [comment]
@osipxd, sorry! I'm overloaded until the end of the year, so if you have time to do it youself it would be great 😅

**Pull request closed without merging**
