### PR TITLE
Added mcMMO, JobsReborn & AureliumSkills Compatibility

### PR DESCRIPTION
**Pull request by MaksyKun**
The PR includes the following in total:
# Added Content #40 
### mcMMO-Compatibility for ItemGenerator #39 :
```
user-requirements-by-level:
    mcmmo-skill:
          unarmed:
            '1': '1:10'
```
### JobsReborn-Compatibility for ItemGenerator #42 :
```
user-requirements-by-level:
    jobs-job:
          miner:
            '1': '1:10'
```
### AureliumSkills-Compatibility (Skills + Stats) for ItemGenerator #41 :
```
user-requirements-by-level:
    aurelium-skill:
          foraging:
            '1': '1:15'
    aurelium-stat:
          strength:
            '1': '1:5'
```

# Changed Content
### Remove Changes of [Commit 1e60ef5](https://github.com/promcteam/prorpgitems/commit/1e60ef55533ca1f7377362903f1c06721c17b070)
The sheduler seemed to prevent my build from using the whole ProRPGItems-Command Syntax. Rolling it back lead to the solution, this could however have another reason.

### CODE REVIEW

**Review by Sentropic — CHANGES_REQUESTED** [review]
As you said on Discord, the in-game editor can't handle the double nested structure of these new requirements, so that still needs to be added. Currently the editor considers them as invalid syntax, so it shows no requirements of each of those types.

Also, I found this issue with Jobs if I try to generate an item without elonging to any job: https://pastebin.com/G3C9aAa6 Maybe there could be similar issues with the other plugins, so check that :)

**Comment by MaksyKun** [comment]
The ingame-editor shall be fixed (at least I tried on local test-server) and the job progession bug is fixed as well.

**Review by Sentropic — CHANGES_REQUESTED** [review]
When creating a new requirement through the editor I managed to cause this exception: https://pastebin.com/zSniSw5C

Try to make it as resilient as possible to people entering invalid data. You can see how in the other submenus, a message is sent to the player when that happens, instead of letting the exception go through 👀.

Also notice that in the pastebin, there seem to be some leftover debug messages, like `{}` and `Item is null`.

Other than that, the nested requirement editor seems great! The null Job is also fixed.

**Comment by Travja** [comment]
This was not ready to merge.

**Pull request merged**
